conscientfootball/config/routes.rb
Conscientfootball::Application.routes.draw do
  resources :facilities

  resources :facebook_contacts

  resources :careers

  resources :school_registrations

  resources :videos

  resources :galleries

  resources :clinic_registrations

  resources :cpfl_registration_news

  resources :cpfl_registrations

  resources :fcbescola_trials

  resources :cryptos
  resources :trial_registrations

  match "/users/sign_up",  :to => redirect{"/users/sign_in"}
  match "/users/password/new",  :to => redirect{"/users/sign_in"}

  devise_for :users
  resources :testimonials
  resources :teams
  resources :resumes
  resources :pages
  resources :awards
  resources :contacts
  resources :projects
  resources :news
  resources :events
  resources :press_releases
  resources :blogs
  resources :metacontents
  resources :redirects
  resources :comments
  resources :site_settings
  resources :assets
    resources :categories

  root :to => 'site#fcbescolanew', :constraints => lambda{|request| request.env['SERVER_NAME'].match('fcbescola.conscientfootball.com')}
  root :to => 'site#fcbclinics', :constraints => lambda{|request| request.env['SERVER_NAME'].match('fcbclinics.conscientfootball.com')}
  match "/admin" , :to => "admin#index"
  match "/trial-registration" , :to => "site#registeration"

  match "/fcbescola-mumbai",  :to => redirect{|p, req| "/fcbescola-football-academy-mumbai?#{req.params.to_query}"}
  match "/fcbescola-delhi",  :to => redirect{|p, req| "/fcbescola-football-academy-delhi?#{req.params.to_query}"}
  root :to => "site#index"
  match "/about-us" , :to => "site#aboutus1"
  match "/our-programs" , :to => "site#ourprogram_new"
  match "/gallery" , :to => "site#gallery"
  match "/gallery-old" , :to => "site#gallery_old"
  match "/gallery-details/:year" , :to => "site#gallery_details"
  match "/gallery-details-new/:year" , :to => "site#gallery_details_new"
  match "/gallery_old/:id" => "site#gallery_old"
  match "/media" , :to => "site#media"
  match "/media/news" , :to => "site#news"
  match "/media/videos" , :to => "site#videos"
  match "/media/online-coverage" , :to => "site#press_release"
  match "/media/blogs" , :to => "site#blog_list"
  match "/contact-us" , :to => "site#contactus"
  match "/join-us" , :to => "site#career"
  match "/football-coaching" , :to => "site#training"
  match "/annual-calendar" , :to => "site#annual_calendar"
  match "/football-camps" , :to => "site#barcelona_clinic"
  match "/football-summer-camps" , :to => "site#summer_camps"
  match "/football-clinic-and-camps" , :to => "site#camps"
  match "/football-tournaments-and-leagues" , :to => "site#cpfl"
  match "/cpfl-form" , :to => "site#cpfl_form"
  match "/faq" , :to => "site#faq"
  match "/faq-overview" , :to => "site#faq_overview"
  match "/fcbse-venue" , :to => "site#fcbse_venue"

match "/site/facility", :to => "site#facility"

  
  match "/gallery-details" , :to => "site#gallery_details"
  match "/gallery-details-new" , :to => "site#gallery_details_new"
  match "/how-we-train" , :to => "site#how_we_train"
  match "/league-table" , :to => "site#league_table"
  match "/our-program-training" , :to => "site#our_program_training"
  match "/overview-fcbescola" , :to => "site#overview_fcbescola"
  match "/rules-regulations" , :to => "site#rules_regulations"
  match "/schedule" , :to => "site#schedule"
  match "/training-program" , :to => "site#training_program"
  match "/view-center" , :to => "site#view_center"
  match "/why-join" , :to => "site#why_join"
  match "/camp-schedule" , :to => "site#camp_schedule"
  match "/upcoming-events" , :to => "site#upcoming_events"
  match "/upcoming-event-details/:id" => "site#upcoming-event-details"
  match "/aboutus1" , :to => "site#aboutus1"
  match "/success-stories" , :to => "site#success_stories"

  match "/facility-management" , :to => "site#mgmt"

  match "/success-stories-details/:id" => "site#success_stories_details"

  match "/about-barca-clinic" , :to => "site#about_barca_clinic"
  match "/terms-and-conditions" , :to => "site#terms_condition"
  match "/fcbescola-goal" , :to => "site#fcbescola_goals"
  match "/registeration" , :to => "site#registeration"
  match "/social-responsibility" , :to => "site#social_responsibility"
  match "/terms-condition-clinics" , :to => "site#terms_condition_clinics"
  match "/privacy-policy" , :to => "site#privacy_policy"
  match "/blog-detail/:id" , :to => "site#blog_details"

  match "/registration_data" , :to => "school_registrations#registration_data"

  match "/fcbescola" , :to => "fcbescola#index"
  match "/fcbescola/trial-registration" , :to => "fcbescola#registeration"

  match "/fcbescola/privacy-policy" , :to => "fcbescola#privacy_policy"
  match "/fcbescola/social-responsibility" , :to => "fcbescola#social_responsibility"
  match "/fcbescola/terms-and-conditions" , :to => "fcbescola#terms_condition"
  post "/regsubmit", :to => "fcbescola#regsubmit"
  post "/regsubmit_delhi", :to => "fcbescola#regsubmit_delhi"

  post "/regsubmit_dwarka", :to => "fcbescola#regsubmit_dwarka"

  match "/fcbescola-football-academy-mumbai" , :to => "fcbescola_mumbai#index"
  match "/fcbescola-mumbai/trial-registration" , :to => "fcbescola_mumbai#registeration"
  match "/fcbescola-mumbai/privacy-policy" , :to => "fcbescola_mumbai#privacy_policy"
  match "/fcbescola-mumbai/social-responsibility" , :to => "fcbescola_mumbai#social_responsibility"
  match "/fcbescola-mumbai/terms-and-conditions" , :to => "fcbescola_mumbai#terms_condition"
  match "/fcbescola-mumbai-juhu-center" , :to => "fcbescola_mumbai#fcbescola_juhu_center"
  match "/fcbescola-mumbai-matunga-center" , :to => "fcbescola_mumbai#fcbescola_matunga_center"
  match "/fcbescola-mumbai-andheri-center" , :to => "fcbescola_mumbai#fcbescola_andheri_center"
  match "/fcbescola-south-mumbai-center" , :to => "fcbescola_mumbai#fcbescola_south_mumbai_center"
  post "/reg_south_mumbai", :to => "fcbescola_mumbai#reg_south_mumbai"
  post "/reg_matunga", :to => "fcbescola_mumbai#reg_matunga"
  post "/reg_andheri", :to => "fcbescola_mumbai#reg_andheri"
  post "/reg_juhu", :to => "fcbescola_mumbai#reg_juhu"

  match "/fcbescola-football-academy-delhi" , :to => "fcbescola_delhi#index"
  match "/fcbescola-delhi/trial-registration" , :to => "fcbescola_delhi#registeration"

  match "/fcbescola-delhi-dwarka-center/trial-registration" , :to => "fcbescola_delhi#registration_dwarka"

  match "/fcbescola-delhi/privacy-policy" , :to => "fcbescola_delhi#privacy_policy"
  match "/fcbescola-delhi/social-responsibility" , :to => "fcbescola_delhi#social_responsibility"
  match "/fcbescola-delhi/terms-and-conditions" , :to => "fcbescola_delhi#terms_condition"

  match "/site/fb_lead" , :to => "site#fb_lead"

  match "/career",  :to => redirect{"/join-us"}
  match "/football-clinic-and-camps/enquiry.html",  :to => redirect{"/football-clinic-and-camps"}
  match "/camps",  :to => redirect{"/football-camps"}
  match "/football-clinic-and-camps/schedule20131112.html",  :to => redirect{"/football-clinic-and-camps"}
  match "/football-clinic-and-camps/index2013dec17.html",  :to => redirect{"/football-clinic-and-camps"}

  match "/football-clinic-and-camps/enquiry5dec2012bkp.html",  :to => redirect{"/football-clinic-and-camps"}
  match "/football-clinic-and-camps/pdf/the-tribune.pdf",  :to => redirect{"/football-clinic-and-camps"}
  match "/football-clinic-and-camps/about.html",  :to => redirect{"/football-clinic-and-camps"}
  match "/football-clinic-and-camps/index20140114.html",  :to => redirect{"/football-clinic-and-camps"}
  match "/football-clinic-and-camps/schedule.html",  :to => redirect{"/football-clinic-and-camps"}
  match "/football-clinic-and-camps/index23dec2013.html",  :to => redirect{"/football-clinic-and-camps"}
  match "/football-clinic-and-camps/schedule_26_june_2014.html",  :to => redirect{"/football-clinic-and-camps"}
  match "/football-clinic-and-camps/index_4_july_2014.html",  :to => redirect{"/football-clinic-and-camps"}
  match "/football-clinic-and-camps/images/",  :to => redirect{"/gallery-details/2016-17"}
  match "/football-clinic-and-camps/news.html",  :to => redirect{"/media"}
  match "/football-clinic-and-camps/pdf/fcbcamps-chandigarh.pdf",  :to => redirect{"/football-camps"}

  match ':controller(/:action(/:id(.:format)))'

 match "(*seo)", :to => "site#not_found", :status => 404

end

conscientfootball/app/models/blog.rb
class Blog < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, :use => :slugged
	validates_presence_of :title, :description
	has_many :comments
	has_one :main_image, :as => :attachable, :dependent => :destroy, :class_name => "Asset",:conditions => {:group_id => "main_image"}
	has_one :thumbnail, :as => :attachable, :dependent => :destroy, :class_name => "Asset",:conditions => {:group_id => "thumbnail"}
	 
	 
 BLOG_MULTIPLE_ASSETS.each do |type|
      self.class_eval <<-EOV
         has_many :assets_#{type}, :as => :attachable, :dependent => :destroy, :class_name => "Asset", :conditions => {:group_id => "assets_#{type}"}, :order => "asset_order ASC"
      EOV
   end
end

conscientfootball/app/controllers/blog_controller.rb
class BlogController < ApplicationController
 before_filter :authenticate_user!
	def blog
		scope=Blog.where(:status => true)
		@pblogs = scope.order("counter DESC")
		@blogs = scope.order("created_at DESC")		
		render :layout => false
	end
	
	def showblog
		scope=Blog.where(:status => true)
		@blogs = scope.order("created_at DESC").limit(2)
		@pblogs =scope.order("counter DESC").limit(2)
		@blog = Blog.find(params[:id])
		@blog.update_attributes(:counter => @blog.counter+1)	
	
		render :layout => false
	end
	
	def addcomment
	  @comment = Comment.new(params[:comment])		
	  if @comment.save
		render :json => {:status => "success"}
	  else
		render :json => {:status => "error"}
	  end
	end

end

conscientfootball/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :authenticate_user!
  # GET /blogs
  # GET /blogs.xml
  
layout "admin"



  def assets
    @blog = Blog.find params[:id]
  end


  def index
    @blogs = Blog.all

    respond_to do |format|
      format.html
      format.xml  { render :xml => @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.xml
  def show
    @blog = Blog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.xml
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.xml
  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to(@blog, :notice => 'Blog was successfully created.') }
        format.xml  { render :xml => @blog, :status => :created, :location => @blog }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @blog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.xml
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to(@blog, :notice => 'Blog was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @blog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.xml
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to(blogs_url) }
      format.xml  { head :ok }
    end
  end
  
  def image_create
	  
  end
  
  

  
  
private
  def sort_column
    Blog.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "desc"
  end
end

conscientfootball/app/helpers/blogs_helper.rb
module BlogsHelper
  
  def url_blog b = ""
      if b.present?
         "/blog/#{b.slug}"
      else
         "/blog"
       end
  end
  
end

conscientfootball/app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :class => "mceEditor" %>
  </div>
  <div class="field">
    <%= f.label :short_description %><br />
    <%= f.text_area :short_description %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :published_on %><br />
    <%= f.date_select :published_on %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :metatitle %><br />
    <%= f.text_field :metatitle %>
  </div>
  <div class="field">
    <%= f.label :metakeyword %><br />
    <%= f.text_area :metakeyword %>
  </div>
  <div class="field">
    <%= f.label :metadescription %><br />
    <%= f.text_area :metadescription %>
  </div>
  <div class="field">
    <%= f.label :featured %><br />
    <%= f.check_box :featured %>
  </div>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

conscientfootball/app/views/blogs/assets.html.erb
<h1>File Uploads</h1>
<script src="/javascripts/asset_handler.js" type="text/javascript"></script>
<% form_for(@blog , :url => '/assets/add', :method => 'post', :html => {:multipart=>true}) do |f| %>
    <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this page from being saved:</h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <input name="entity_id" value="<%= @blog.id %>" type="hidden" />
    <%= render :partial => "assets/singular_assets", :locals => {:for_class => "Blog", :entity => @blog, :asset_types => ["main_image", "thumbnail"]} %>
  <%= render :partial => "assets/assets", :locals => {:for_class => "blog", :entity => @blog} %>
    <br clear="all"/>    <br clear="all"/>
  <p align="center">
    <%= f.submit 'Update', :class=> "admin-main-button" %>
  </p>
<% end %>

conscientfootball/app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

conscientfootball/app/views/blogs/index.html.erb
<h1>Listing blogs</h1>

<table class="table table-striped   table-responsive" width="100%"  cellpadding="10">
  <tr>
    <th>Title</th>
    <th>Status</th>
    <th>Published on</th>
    <th>Category</th>
     <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.status %></td>
    <td><%= blog.published_on %></td>
    <td><%= blog.category %></td>
    <td><a href="/blogs/assets/<%= blog.id%>" class="round button1">Add Images</a></td>
    <td><%= link_to 'Show', blog %></td>
    <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
    <td><%= link_to 'Destroy', blog, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<%= link_to 'New Blog', new_blog_path %>

conscientfootball/app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

conscientfootball/app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

<p>
  <b>Title:</b>
  <%= @blog.title %>
</p>

<p>
  <b>Description:</b>
  <%= @blog.description %>
</p>

<p>
  <b>Short description:</b>
  <%= @blog.short_description %>
</p>

<p>
  <b>Slug:</b>
  <%= @blog.slug %>
</p>

<p>
  <b>Status:</b>
  <%= @blog.status %>
</p>

<p>
  <b>Published on:</b>
  <%= @blog.published_on %>
</p>

<p>
  <b>Category:</b>
  <%= @blog.category %>
</p>

<p>
  <b>Metatitle:</b>
  <%= @blog.metatitle %>
</p>

<p>
  <b>Metakeyword:</b>
  <%= @blog.metakeyword %>
</p>

<p>
  <b>Metadescription:</b>
  <%= @blog.metadescription %>
</p>




<h1>Listing comments</h1>

<table class="scaffolded" width="100%"  cellpadding="10">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Comment</th>
    <th>Blog</th>
    <th>Approved</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blog.comments.each do |comment| %>
  <tr>
    <td><%= comment.name %></td>
    <td><%= comment.email %></td>
    <td><%= comment.comment %></td>
    <td><%= comment.blog_id %></td>
    <td><%= comment.approved %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>