conscientfootball/config/routes.rb
Conscientfootball::Application.routes.draw do
  resources :facilities

  resources :facebook_contacts

  resources :careers

  resources :school_registrations

  resources :videos

  resources :galleries

  resources :clinic_registrations

  resources :cpfl_registration_news

  resources :cpfl_registrations

  resources :fcbescola_trials

  resources :cryptos
  resources :trial_registrations

  match "/users/sign_up",  :to => redirect{"/users/sign_in"}
  match "/users/password/new",  :to => redirect{"/users/sign_in"}

  devise_for :users
  resources :testimonials
  resources :teams
  resources :resumes
  resources :pages
  resources :awards
  resources :contacts
  resources :projects
  resources :news
  resources :events
  resources :press_releases
  resources :blogs
  resources :metacontents
  resources :redirects
  resources :comments
  resources :site_settings
  resources :assets
    resources :categories

  root :to => 'site#fcbescolanew', :constraints => lambda{|request| request.env['SERVER_NAME'].match('fcbescola.conscientfootball.com')}
  root :to => 'site#fcbclinics', :constraints => lambda{|request| request.env['SERVER_NAME'].match('fcbclinics.conscientfootball.com')}
  match "/admin" , :to => "admin#index"
  match "/trial-registration" , :to => "site#registeration"

  match "/fcbescola-mumbai",  :to => redirect{|p, req| "/fcbescola-football-academy-mumbai?#{req.params.to_query}"}
  match "/fcbescola-delhi",  :to => redirect{|p, req| "/fcbescola-football-academy-delhi?#{req.params.to_query}"}
  root :to => "site#index"
  match "/about-us" , :to => "site#aboutus1"
  match "/our-programs" , :to => "site#ourprogram_new"
  match "/gallery" , :to => "site#gallery"
  match "/gallery-old" , :to => "site#gallery_old"
  match "/gallery-details/:year" , :to => "site#gallery_details"
  match "/gallery-details-new/:year" , :to => "site#gallery_details_new"
  match "/gallery_old/:id" => "site#gallery_old"
  match "/media" , :to => "site#media"
  match "/media/news" , :to => "site#news"
  match "/media/videos" , :to => "site#videos"
  match "/media/online-coverage" , :to => "site#press_release"
  match "/media/blogs" , :to => "site#blog_list"
  match "/contact-us" , :to => "site#contactus"
  match "/join-us" , :to => "site#career"
  match "/football-coaching" , :to => "site#training"
  match "/annual-calendar" , :to => "site#annual_calendar"
  match "/football-camps" , :to => "site#barcelona_clinic"
  match "/football-summer-camps" , :to => "site#summer_camps"
  match "/football-clinic-and-camps" , :to => "site#camps"
  match "/football-tournaments-and-leagues" , :to => "site#cpfl"
  match "/cpfl-form" , :to => "site#cpfl_form"
  match "/faq" , :to => "site#faq"
  match "/faq-overview" , :to => "site#faq_overview"
  match "/fcbse-venue" , :to => "site#fcbse_venue"

match "/site/facility", :to => "site#facility"

  
  match "/gallery-details" , :to => "site#gallery_details"
  match "/gallery-details-new" , :to => "site#gallery_details_new"
  match "/how-we-train" , :to => "site#how_we_train"
  match "/league-table" , :to => "site#league_table"
  match "/our-program-training" , :to => "site#our_program_training"
  match "/overview-fcbescola" , :to => "site#overview_fcbescola"
  match "/rules-regulations" , :to => "site#rules_regulations"
  match "/schedule" , :to => "site#schedule"
  match "/training-program" , :to => "site#training_program"
  match "/view-center" , :to => "site#view_center"
  match "/why-join" , :to => "site#why_join"
  match "/camp-schedule" , :to => "site#camp_schedule"
  match "/upcoming-events" , :to => "site#upcoming_events"
  match "/upcoming-event-details/:id" => "site#upcoming-event-details"
  match "/aboutus1" , :to => "site#aboutus1"
  match "/success-stories" , :to => "site#success_stories"

  match "/facility-management" , :to => "site#mgmt"

  match "/success-stories-details/:id" => "site#success_stories_details"

  match "/about-barca-clinic" , :to => "site#about_barca_clinic"
  match "/terms-and-conditions" , :to => "site#terms_condition"
  match "/fcbescola-goal" , :to => "site#fcbescola_goals"
  match "/registeration" , :to => "site#registeration"
  match "/social-responsibility" , :to => "site#social_responsibility"
  match "/terms-condition-clinics" , :to => "site#terms_condition_clinics"
  match "/privacy-policy" , :to => "site#privacy_policy"
  match "/blog-detail/:id" , :to => "site#blog_details"

  match "/registration_data" , :to => "school_registrations#registration_data"

  match "/fcbescola" , :to => "fcbescola#index"
  match "/fcbescola/trial-registration" , :to => "fcbescola#registeration"

  match "/fcbescola/privacy-policy" , :to => "fcbescola#privacy_policy"
  match "/fcbescola/social-responsibility" , :to => "fcbescola#social_responsibility"
  match "/fcbescola/terms-and-conditions" , :to => "fcbescola#terms_condition"
  post "/regsubmit", :to => "fcbescola#regsubmit"
  post "/regsubmit_delhi", :to => "fcbescola#regsubmit_delhi"

  post "/regsubmit_dwarka", :to => "fcbescola#regsubmit_dwarka"

  match "/fcbescola-football-academy-mumbai" , :to => "fcbescola_mumbai#index"
  match "/fcbescola-mumbai/trial-registration" , :to => "fcbescola_mumbai#registeration"
  match "/fcbescola-mumbai/privacy-policy" , :to => "fcbescola_mumbai#privacy_policy"
  match "/fcbescola-mumbai/social-responsibility" , :to => "fcbescola_mumbai#social_responsibility"
  match "/fcbescola-mumbai/terms-and-conditions" , :to => "fcbescola_mumbai#terms_condition"
  match "/fcbescola-mumbai-juhu-center" , :to => "fcbescola_mumbai#fcbescola_juhu_center"
  match "/fcbescola-mumbai-matunga-center" , :to => "fcbescola_mumbai#fcbescola_matunga_center"
  match "/fcbescola-mumbai-andheri-center" , :to => "fcbescola_mumbai#fcbescola_andheri_center"
  match "/fcbescola-south-mumbai-center" , :to => "fcbescola_mumbai#fcbescola_south_mumbai_center"
  post "/reg_south_mumbai", :to => "fcbescola_mumbai#reg_south_mumbai"
  post "/reg_matunga", :to => "fcbescola_mumbai#reg_matunga"
  post "/reg_andheri", :to => "fcbescola_mumbai#reg_andheri"
  post "/reg_juhu", :to => "fcbescola_mumbai#reg_juhu"

  match "/fcbescola-football-academy-delhi" , :to => "fcbescola_delhi#index"
  match "/fcbescola-delhi/trial-registration" , :to => "fcbescola_delhi#registeration"

  match "/fcbescola-delhi-dwarka-center/trial-registration" , :to => "fcbescola_delhi#registration_dwarka"

  match "/fcbescola-delhi/privacy-policy" , :to => "fcbescola_delhi#privacy_policy"
  match "/fcbescola-delhi/social-responsibility" , :to => "fcbescola_delhi#social_responsibility"
  match "/fcbescola-delhi/terms-and-conditions" , :to => "fcbescola_delhi#terms_condition"

  match "/site/fb_lead" , :to => "site#fb_lead"

  match "/career",  :to => redirect{"/join-us"}
  match "/football-clinic-and-camps/enquiry.html",  :to => redirect{"/football-clinic-and-camps"}
  match "/camps",  :to => redirect{"/football-camps"}
  match "/football-clinic-and-camps/schedule20131112.html",  :to => redirect{"/football-clinic-and-camps"}
  match "/football-clinic-and-camps/index2013dec17.html",  :to => redirect{"/football-clinic-and-camps"}

  match "/football-clinic-and-camps/enquiry5dec2012bkp.html",  :to => redirect{"/football-clinic-and-camps"}
  match "/football-clinic-and-camps/pdf/the-tribune.pdf",  :to => redirect{"/football-clinic-and-camps"}
  match "/football-clinic-and-camps/about.html",  :to => redirect{"/football-clinic-and-camps"}
  match "/football-clinic-and-camps/index20140114.html",  :to => redirect{"/football-clinic-and-camps"}
  match "/football-clinic-and-camps/schedule.html",  :to => redirect{"/football-clinic-and-camps"}
  match "/football-clinic-and-camps/index23dec2013.html",  :to => redirect{"/football-clinic-and-camps"}
  match "/football-clinic-and-camps/schedule_26_june_2014.html",  :to => redirect{"/football-clinic-and-camps"}
  match "/football-clinic-and-camps/index_4_july_2014.html",  :to => redirect{"/football-clinic-and-camps"}
  match "/football-clinic-and-camps/images/",  :to => redirect{"/gallery-details/2016-17"}
  match "/football-clinic-and-camps/news.html",  :to => redirect{"/media"}
  match "/football-clinic-and-camps/pdf/fcbcamps-chandigarh.pdf",  :to => redirect{"/football-camps"}

  match ':controller(/:action(/:id(.:format)))'

 match "(*seo)", :to => "site#not_found", :status => 404

end

conscientfootball/app/models/metacontent.rb
class Metacontent < ActiveRecord::Base
end

conscientfootball/app/controllers/metacontents_controller.rb
class MetacontentsController < ApplicationController
  before_filter :authenticate_user!
  # GET /metacontents
  # GET /metacontents.xml
layout "admin"
  def index
    @metacontents = Metacontent.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @metacontents }
    end
  end

  # GET /metacontents/1
  # GET /metacontents/1.xml
  def show
    @metacontent = Metacontent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @metacontent }
    end
  end

  # GET /metacontents/new
  # GET /metacontents/new.xml
  def new
    @metacontent = Metacontent.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @metacontent }
    end
  end

  # GET /metacontents/1/edit
  def edit
    @metacontent = Metacontent.find(params[:id])
  end

  # POST /metacontents
  # POST /metacontents.xml
  def create
    @metacontent = Metacontent.new(params[:metacontent])

    respond_to do |format|
      if @metacontent.save
        format.html { redirect_to(@metacontent, :notice => 'Metacontent was successfully created.') }
        format.xml  { render :xml => @metacontent, :status => :created, :location => @metacontent }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @metacontent.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /metacontents/1
  # PUT /metacontents/1.xml
  def update
    @metacontent = Metacontent.find(params[:id])

    respond_to do |format|
      if @metacontent.update_attributes(params[:metacontent])
        format.html { redirect_to(@metacontent, :notice => 'Metacontent was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @metacontent.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /metacontents/1
  # DELETE /metacontents/1.xml
  def destroy
    @metacontent = Metacontent.find(params[:id])
    @metacontent.destroy

    respond_to do |format|
      format.html { redirect_to(metacontents_url) }
      format.xml  { head :ok }
    end
  end
  private
  def sort_column
    Metacontent.column_names.include?(params[:sort]) ? params[:sort] : "url"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end

end

conscientfootball/app/views/metacontents/_form.html.erb
<%= form_for(@metacontent) do |f| %>
  <% if @metacontent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@metacontent.errors.count, "error") %> prohibited this metacontent from being saved:</h2>

      <ul>
      <% @metacontent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>	
  <div class="field">
    <%= f.label :meta_titles %><br />
    <%= f.text_area :meta_titles %>
  </div>
  <div class="field">
    <%= f.label :meta_keywords %><br />
    <%= f.text_area :meta_keywords %>
  </div>
  <div class="field">
    <%= f.label :meta_description %><br />
    <%= f.text_area :meta_description %>
  </div>
  <div class="field">
    <%= f.label :meta_content %><br />
    <%= f.text_area :meta_content %>
  </div>
  <div class="field">
    <%= f.label :meta_text %><br />
    <%= f.text_area :meta_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

conscientfootball/app/views/metacontents/edit.html.erb
<h1>Editing metacontent</h1>

<%= render 'form' %>

<%= link_to 'Show', @metacontent %> |
<%= link_to 'Back', metacontents_path %>

conscientfootball/app/views/metacontents/index.html.erb
<h1>Listing metacontents <%= link_to 'New Metacontent', new_metacontent_path%></h1>


<table class="table table-striped table-bordered" width="100%"  cellpadding="10">
  <tr>
	
    <th>Url</th>
    <th>Meta Titles</th>
    <th>Meta Keywords</th>
    <th>Meta Description</th>
    <th>Meta Content</th>
    <th>Meta Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @metacontents.each do |metacontent| %>
  <tr>
    <td><%= metacontent.url %></td>
    <td><%= metacontent.meta_titles %></td>
    <td><%= metacontent.meta_keywords %></td>
    <td><%= metacontent.meta_description %></td>
    <td><%= metacontent.meta_content %></td>
    <td><%= metacontent.meta_text %></td>
    <td><%= link_to 'Show', metacontent %></td>
    <td><%= link_to 'Edit', edit_metacontent_path(metacontent) %></td>
    <td><%= link_to 'Destroy', metacontent, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

conscientfootball/app/views/metacontents/new.html.erb
<h1>New metacontent</h1>

<%= render 'form' %>

<%= link_to 'Back', metacontents_path %>

conscientfootball/app/views/metacontents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Meta titles:</b>
  <%= @metacontent.meta_titles %>
</p>

<p>
  <b>Meta keywords:</b>
  <%= @metacontent.meta_keywords %>
</p>

<p>
  <b>Meta description:</b>
  <%= @metacontent.meta_description %>
</p>

<p>
  <b>Meta content:</b>
  <%= @metacontent.meta_content %>
</p>

<p>
  <b>Meta text:</b>
  <%= @metacontent.meta_text %>
</p>


<%= link_to 'Edit', edit_metacontent_path(@metacontent) %> |
<%= link_to 'Back', metacontents_path %>